-- =============================================================================
-- db/procedures/payments.sql
-- =============================================================================
-- Purpose:
--   Stored procedure for recording a payment against a booking's bill.
--   Updates the bill's running total (amount_paid, outstanding_balance, and
--   balance_flag) atomically after inserting the payment row.
--
-- Procedure to implement:
--   CREATE OR REPLACE PROCEDURE record_payment(
--       p_booking_id    UUID,
--       p_amount        NUMERIC(10,2),
--       p_payment_method VARCHAR(50),
--       p_notes         VARCHAR(255) DEFAULT NULL
--   )
--   LANGUAGE plpgsql
--   AS $$
--   DECLARE
--       v_new_paid    NUMERIC(10,2);
--       v_outstanding NUMERIC(10,2);
--       v_total       NUMERIC(10,2);
--   BEGIN
--       -- Step 1: Validate — a bill must exist before recording a payment
--       IF NOT EXISTS (SELECT 1 FROM bill WHERE booking_id = p_booking_id) THEN
--           RAISE EXCEPTION 'No bill found for booking %. Generate the bill first.', p_booking_id;
--       END IF;
--
--       -- Step 2: Insert the payment transaction row
--       INSERT INTO payment (booking_id, amount, payment_method, notes, paid_at)
--       VALUES (p_booking_id, p_amount, p_payment_method, p_notes, NOW());
--
--       -- Step 3: Recalculate bill totals
--       SELECT total_amount INTO v_total FROM bill WHERE booking_id = p_booking_id;
--       SELECT COALESCE(SUM(amount), 0.00) INTO v_new_paid
--         FROM payment WHERE booking_id = p_booking_id;
--
--       v_outstanding := GREATEST(v_total - v_new_paid, 0.00);
--
--       -- Step 4: Update bill row
--       UPDATE bill SET
--           amount_paid         = v_new_paid,
--           outstanding_balance = v_outstanding,
--           balance_flag        = (v_outstanding > 0)
--       WHERE booking_id = p_booking_id;
--   END;
--   $$;
--
-- Notes:
--   - GREATEST(..., 0) prevents negative outstanding_balance in case of overpayment.
--   - Multiple payments for the same booking are supported — each call adds a new
--     payment row and updates the cumulative total.
--
-- Called by:
--   POST /api/payments endpoint in backend/app/routers/billing.py
-- =============================================================================

-- TODO: Implement record_payment procedure
